/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mesos;

import org.junit.Test;
import static org.hamcrest.CoreMatchers.*;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        assertThat(false, is(false));
    }
}
