jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  numExecutors: 0
  clouds:
    - mesos:
        agentUser: "${JENKINS_AGENT_USER:-root}"
        frameworkName: "${JENKINS_FRAMEWORK_NAME:-Jenkins Scheduler}"
        jenkinsUrl: "http://${JENKINS_FRAMEWORK_NAME:-jenkins}.${MARATHON_NAME:-marathon}.mesos:${PORT0:-8080}"
        mesosAgentSpecTemplates:
          - containerImage: "amazoncorretto:8"
            cpus: "0.1"
            defaultAgent: false
            disk: "0.0"
            executorMem: 128
            idleTerminationMinutes: 3
            jnlpArgs: "-noReconnect"
            jvmArgs: "-Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true"
            label: "mesos"
            maxExecutors: 1
            mem: 512
            minExecutors: 1
            mode: NORMAL
        mesosMasterUrl: "${JENKINS_MESOS_MASTER:-http://leader.mesos:5050}"
        role: "${JENKINS_AGENT_ROLE:-*}"
unclassified:
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins.marathon.mesos:${PORT0:-8080}/"