jenkins:
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  numExecutors: 0
  clouds:
    - mesos:
        agentUser: "${JENKINS_AGENT_USER:-root}"
        frameworkName: "${JENKINS_FRAMEWORK_NAME:-Jenkins Scheduler}"
        jenkinsUrl: "http://${JENKINS_FRAMEWORK_NAME:-jenkins}.${MARATHON_NAME:-marathon}.mesos:${PORT0:-8080}"
        mesosAgentSpecTemplates:
          - label: "linux"
            agentAttributes: ""
            agentCommandStyle: Linux
            containerInfo:
              dockerForcePullImage: false
              dockerImage: "amazoncorretto:8"
              dockerPrivilegedMode: false
              isDind: false
              networking: HOST
              type: "DOCKER"
            cpus: 0.1
            disk: 0.0
            domainFilterModel: "home"
            idleTerminationMinutes: 3
            jnlpArgs: "-noReconnect"
            jvmArgs: "-Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true"
            maxExecutors: 1
            mem: 512
            minExecutors: 1
            mode: EXCLUSIVE 
          - label: "windows"
            agentAttributes: "os:windows"
            agentCommandStyle: Windows
            containerInfo:
              dockerForcePullImage: false
              dockerImage: "winamd64/openjdk:8-jre-windowsservercore-1809"
              dockerPrivilegedMode: false
              isDind: false
              networking: BRIDGE
              type: "DOCKER"
            cpus: 0.1
            disk: 0.0
            domainFilterModel: "any"
            idleTerminationMinutes: 3
            jnlpArgs: "-noReconnect"
            maxExecutors: 1
            mem: 512
            minExecutors: 1
            mode: EXCLUSIVE 
        mesosMasterUrl: "${JENKINS_MESOS_MASTER:-http://leader.mesos:5050}"
        role: "${JENKINS_AGENT_ROLE:-*}"
unclassified:
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jenkins.marathon.mesos:${PORT0:-8080}/"
