name: GitHub CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: sudo ci/github.sh
    - name: Cleanup
      run: sudo docker kill mini
